In [ ]:
!pip install pandas
!pip install numpy

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('Zomato-data-.csv')

In [ ]:
df

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet
...,...,...,...,...,...,...,...
143,Melting Melodies,No,No,3.3/5,0,100,Dining
144,New Indraprasta,No,No,3.3/5,0,150,Dining
145,Anna Kuteera,Yes,No,4.0/5,771,450,Dining
146,Darbar,No,No,3.0/5,98,800,Dining
147,Vijayalakshmi,Yes,No,3.9/5,47,200,Dining

In [ ]:
df.head()

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet

In [7]:
df.shape

(148, 7)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148 entries, 0 to 147
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         148 non-null    object
 1   online_order                 148 non-null    object
 2   book_table                   148 non-null    object
 3   rate                         148 non-null    object
 4   votes                        148 non-null    int64
 5   approx_cost(for two people)  148 non-null    int64
 6   listed_in(type)              148 non-null    object
dtypes: int64(2), object(5)
memory usage: 8.2+ KB

In [9]:
df.describe()

             votes  approx_cost(for two people)
count   148.000000                   148.000000
mean    264.810811                   418.243243
std     653.676951                   223.085098
min       0.000000                   100.000000
25%       6.750000                   200.000000
50%      43.500000                   400.000000
75%     221.750000                   600.000000
max    4884.000000                   950.000000

In [10]:
df.isnull().sum()

name                           0
online_order                   0
book_table                     0
rate                           0
votes                          0
approx_cost(for two people)    0
listed_in(type)                0
dtype: int64

In [13]:
# 1.How many restaurants offer online order?
df['online_order'].value_counts()

online_order
No     90
Yes    58
Name: count, dtype: int64

In [16]:
 # 2.What is the average rating?
df['rate'].head(10)

0    4.1/5
1    4.1/5
2    3.8/5
3    3.7/5
4    3.8/5
5    3.8/5
6    3.6/5
7    4.6/5
8    4.0/5
9    4.2/5
Name: rate, dtype: object

In [17]:
# Step 2 - remove '/5' and convert to number
df['rate'] = df['rate'].str.split('/').str[0]
df['rate'] = pd.to_numeric(df['rate'], errors='coerce')

In [18]:
# Step 3 - now mean will work!
df['rate'].mean()

np.float64(3.6331081081081082)

In [19]:
# 3. Which type of restaurant is most common?
df['listed_in(type)'].value_counts()

listed_in(type)
Dining    110
Cafes      23
other       8
Buffet      7
Name: count, dtype: int64

In [20]:
# 4.What is the average cost for two people?
df['approx_cost(for two people)'].mean()

np.float64(418.2432432432432)

In [22]:
# 5.Which are the top 10 highest rated restaurants?
df[['name','rate']].sort_values('rate', ascending=False).head(10)

                      name  rate
7                   Onesta   4.6
44                  Onesta   4.6
38       Empire Restaurant   4.4
86           Meghana Foods   4.4
52  Corner House Ice Cream   4.3
57                  Wamama   4.2
60           Peppy Peppers   4.2
81           Frozen Bottle   4.2
34                  Faasos   4.2
12        The Coffee Shack   4.2

In [26]:
# 6.Which restaurant has the most votes?
df[['name','votes']].sort_values('votes', ascending=False).head(1)

                 name  votes
38  Empire Restaurant   4884

In [27]:
# 7. How many restaurants accept online orders vs don't?
df['online_order'].value_counts()

online_order
No     90
Yes    58
Name: count, dtype: int64

In [29]:
# 8.What is the most expensive and cheapest cost for two people?
print('Most Expensive', df['approx_cost(for two people)'].max())
print('Cheapest',df['approx_cost(for two people)'].min())
print('Average Cost',df['approx_cost(for two people)'].mean())

Most Expensive 950
Cheapest 100
Average Cost 418.2432432432432

In [30]:
# 9.Average rating for restaurants WITH online order vs WITHOUT?
df.groupby('online_order')['rate'].mean()

online_order
No     3.487778
Yes    3.858621
Name: rate, dtype: float64

In [31]:
# 10. Which type of restaurant has highest average rating?
df.groupby('listed_in(type)')['rate'].mean().sort_values(ascending=False)

listed_in(type)
other     3.912500
Buffet    3.842857
Cafes     3.765217
Dining    3.571818
Name: rate, dtype: float64

In [32]:
# 11. What is the total votes per restaurant type?
df.groupby('listed_in(type)')['votes'].mean().sort_values(ascending=False)

listed_in(type)
other     1170.875000
Buffet     432.571429
Cafes      279.739130
Dining     185.118182
Name: votes, dtype: float64

In [33]:
# 12. Which restaurant type has the most expensive average cost?
df.groupby('listed_in(type)')['approx_cost(for two people)'].mean().sort_values(ascending=False)

listed_in(type)
Buffet    671.428571
other     668.750000
Cafes     545.652174
Dining    357.272727
Name: approx_cost(for two people), dtype: float64

In [38]:
# 13. How many restaurants have rating above 4?
df[df['rate']>4].shape[0]

24

In [42]:
# 14. Show only restaurants with rating above 4 AND online order available
df.loc[(df['rate'] > 4) & (df['online_order'] =='Yes')]

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1,775,800,Buffet
1,Spice Elephant,Yes,No,4.1,787,800,Buffet
7,Onesta,Yes,Yes,4.6,2556,600,Cafes
9,Smacznego,Yes,No,4.2,504,550,Cafes
10,Village Café,Yes,No,4.1,402,500,Cafes
11,Cafe Shuffle,Yes,Yes,4.2,150,600,Cafes
12,The Coffee Shack,Yes,Yes,4.2,164,500,Cafes
34,Faasos,Yes,No,4.2,415,500,other
37,Szechuan Dragon,Yes,No,4.2,1647,600,Dining
38,Empire Restaurant,Yes,No,4.4,4884,750,other
44,Onesta,Yes,Yes,4.6,2556,600,other
51,Shree Cool Point,Yes,No,4.1,28,150,Dining
57,Wamama,Yes,Yes,4.2,354,800,other
65,Kabab Magic,Yes,No,4.1,1720,400,Dining
76,Sri Guru Kottureshwara Davangere Benne Dosa,Yes,No,4.1,558,150,Dining
81,Frozen Bottle,Yes,No,4.2,146,400,Dining
86,Meghana Foods,Yes,No,4.4,4401,600,Dining
120,Bengaluru Coffee House,Yes,No,4.1,201,300,Dining

In [43]:
# 15. What percentage of restaurants offer online ordering?
online = df['online_order'].value_counts()
percentage = (online['Yes'] / len(df)) * 100
print(f'{percentage:.2f}% restaurants offer online ordering')

39.19% restaurants offer online ordering

In [45]:
# 16.  Top 5 most voted restaurants with their rating
df[['name','votes','rate']].sort_values('votes', ascending=False).head(5)

                 name  votes  rate
38  Empire Restaurant   4884   4.4
86      Meghana Foods   4401   4.4
7              Onesta   2556   4.6
44             Onesta   2556   4.6
65        Kabab Magic   1720   4.1

In [46]:
# 17. Add a new column 'value_for_money'
# If cost < 300 AND rate > 4 = 'High'
# else = 'Low'
df['value_for_money'] = np.where(
    (df['approx_cost(for two people)'] < 300) & (df['rate'] > 4),
    'High',
    'Low'
)
df[['name', 'rate', 'approx_cost(for two people)', 'value_for_money']].head(10)

,name,rate,approx_cost(for two people),value_for_money
0,Jalsa,4.1,800,Low
1,Spice Elephant,4.1,800,Low
2,San Churro Cafe,3.8,800,Low
3,Addhuri Udupi Bhojana,3.7,300,Low
4,Grand Village,3.8,600,Low
5,Timepass Dinner,3.8,600,Low
6,Rosewood International Hotel - Bar & Restaurant,3.6,800,Low
7,Onesta,4.6,600,Low
8,Penthouse Cafe,4.0,700,Low
9,Smacznego,4.2,550,Low

In [47]:
# 18.How many restaurants are High vs Low value for money?
df['value_for_money'].value_counts()

value_for_money
Low     144
High      4
Name: count, dtype: int64

In [48]:
# 19. Average rating for High vs Low value restaurants
df.groupby('value_for_money')['rate'].mean()

value_for_money
High    4.100000
Low     3.620139
Name: rate, dtype: float64

In [49]:
# 20. Save your cleaned and analysed data to CSV
df.to_csv('Zomato_cleaned.csv', index=False)
print('File saved successfully!')

File saved successfully!